version: "3"
name: signet
services:
  api:
    container_name: api
    build:
      context: .
    expose:
      - 5001
    environment:
      - PORT=5001
    networks:
      network:
        ipv4_address: 172.19.0.2

networks:
  network:
    ipam:
      config:
        - subnet: 172.19.0.0/24
