version: "3"
name: signet
services:
  api:
    restart: unless-stopped
    build:
      context: .
    expose:
      - 5001
    environment:
      - PORT=5001
      - AUTHLIB_INSECURE_TRANSPORT=1
    # entrypoint: [ "tail", "-f", "/dev/null" ]
    networks:
      network:
        ipv4_address: 172.19.1.2

  postgres:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/prod/db_postgres:/var/lib/postgresql/data
      - ./db/postgres/scripts:/docker-entrypoint-initdb.d
    expose:
      - 5432
    networks:
      network:
        ipv4_address: 172.19.1.3

# sudo docker compose -f "docker-compose-prod.yml" run --rm pgbackup
  pgbackup:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PROJ_NAME=${COMPOSE_PROJECT_NAME}
    volumes:
      - /opt/sca/postgres_backups:/backup
    networks:
      - network
    command: >
      bash -c "pg_dump -w -f /backup/$${PROJ_NAME}_postgres_backup.$$(date +%F).psql --username=$$POSTGRES_USER --host=postgres --dbname=$$POSTGRES_DB"

networks:
  network:
    ipam:
      config:
        - subnet: 172.19.1.0/24
