version: "3"
name: signet
services:
  postgres:
    container_name: postgres
    image: postgres:14.5
    # restart: unless-stopped
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=app
    volumes:
      - ./db/db_postgres:/var/lib/postgresql/data
      - ./db/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
    expose:
      - 5432
